package com.mycompany.config.plan;
// Generated Feb 7, 2016 11:27:39 AM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * ActivityContext generated by hbm2java
 */
public class ActivityContext  implements java.io.Serializable {


     private BigDecimal activitycontextid;
     private long version;
     private PlanContext planContext;
     private Activity activity;
     private ActivityDefinition activityDefinition;
     private String state;
     private String prevstate;
     private BigDecimal stdescid;
     private BigDecimal serviceproviderid;
     private Boolean haserror;
     private Boolean hasduedateitem;
     private String value1;
     private String value2;
     private String value3;
     private String value4;
     private String value5;
     private String value6;
     private String value7;
     private String value8;
     private String value9;
     private String value10;
     private BigDecimal regionidsys;
     private BigDecimal sessionid;
     private Date lstmoddttm;
     private Set activityDetails = new HashSet(0);

    public ActivityContext() {
    }

	
    public ActivityContext(BigDecimal activitycontextid, Activity activity, ActivityDefinition activityDefinition, BigDecimal sessionid, Date lstmoddttm) {
        this.activitycontextid = activitycontextid;
        this.activity = activity;
        this.activityDefinition = activityDefinition;
        this.sessionid = sessionid;
        this.lstmoddttm = lstmoddttm;
    }
    public ActivityContext(BigDecimal activitycontextid, PlanContext planContext, Activity activity, ActivityDefinition activityDefinition, String state, String prevstate, BigDecimal stdescid, BigDecimal serviceproviderid, Boolean haserror, Boolean hasduedateitem, String value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, BigDecimal regionidsys, BigDecimal sessionid, Date lstmoddttm, Set activityDetails) {
       this.activitycontextid = activitycontextid;
       this.planContext = planContext;
       this.activity = activity;
       this.activityDefinition = activityDefinition;
       this.state = state;
       this.prevstate = prevstate;
       this.stdescid = stdescid;
       this.serviceproviderid = serviceproviderid;
       this.haserror = haserror;
       this.hasduedateitem = hasduedateitem;
       this.value1 = value1;
       this.value2 = value2;
       this.value3 = value3;
       this.value4 = value4;
       this.value5 = value5;
       this.value6 = value6;
       this.value7 = value7;
       this.value8 = value8;
       this.value9 = value9;
       this.value10 = value10;
       this.regionidsys = regionidsys;
       this.sessionid = sessionid;
       this.lstmoddttm = lstmoddttm;
       this.activityDetails = activityDetails;
    }
   
    public BigDecimal getActivitycontextid() {
        return this.activitycontextid;
    }
    
    public void setActivitycontextid(BigDecimal activitycontextid) {
        this.activitycontextid = activitycontextid;
    }
    public long getVersion() {
        return this.version;
    }
    
    public void setVersion(long version) {
        this.version = version;
    }
    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
    public PlanContext getPlanContext() {
        return this.planContext;
    }
    
    public void setPlanContext(PlanContext planContext) {
        this.planContext = planContext;
    }
    public Activity getActivity() {
        return this.activity;
    }
    
    public void setActivity(Activity activity) {
        this.activity = activity;
    }
    public ActivityDefinition getActivityDefinition() {
        return this.activityDefinition;
    }
    
    public void setActivityDefinition(ActivityDefinition activityDefinition) {
        this.activityDefinition = activityDefinition;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getPrevstate() {
        return this.prevstate;
    }
    
    public void setPrevstate(String prevstate) {
        this.prevstate = prevstate;
    }
    public BigDecimal getStdescid() {
        return this.stdescid;
    }
    
    public void setStdescid(BigDecimal stdescid) {
        this.stdescid = stdescid;
    }
    public BigDecimal getServiceproviderid() {
        return this.serviceproviderid;
    }
    
    public void setServiceproviderid(BigDecimal serviceproviderid) {
        this.serviceproviderid = serviceproviderid;
    }
    public Boolean getHaserror() {
        return this.haserror;
    }
    
    public void setHaserror(Boolean haserror) {
        this.haserror = haserror;
    }
    public Boolean getHasduedateitem() {
        return this.hasduedateitem;
    }
    
    public void setHasduedateitem(Boolean hasduedateitem) {
        this.hasduedateitem = hasduedateitem;
    }
    public String getValue1() {
        return this.value1;
    }
    
    public void setValue1(String value1) {
        this.value1 = value1;
    }
    public String getValue2() {
        return this.value2;
    }
    
    public void setValue2(String value2) {
        this.value2 = value2;
    }
    public String getValue3() {
        return this.value3;
    }
    
    public void setValue3(String value3) {
        this.value3 = value3;
    }
    public String getValue4() {
        return this.value4;
    }
    
    public void setValue4(String value4) {
        this.value4 = value4;
    }
    public String getValue5() {
        return this.value5;
    }
    
    public void setValue5(String value5) {
        this.value5 = value5;
    }
    public String getValue6() {
        return this.value6;
    }
    
    public void setValue6(String value6) {
        this.value6 = value6;
    }
    public String getValue7() {
        return this.value7;
    }
    
    public void setValue7(String value7) {
        this.value7 = value7;
    }
    public String getValue8() {
        return this.value8;
    }
    
    public void setValue8(String value8) {
        this.value8 = value8;
    }
    public String getValue9() {
        return this.value9;
    }
    
    public void setValue9(String value9) {
        this.value9 = value9;
    }
    public String getValue10() {
        return this.value10;
    }
    
    public void setValue10(String value10) {
        this.value10 = value10;
    }
    public BigDecimal getRegionidsys() {
        return this.regionidsys;
    }
    
    public void setRegionidsys(BigDecimal regionidsys) {
        this.regionidsys = regionidsys;
    }
    public BigDecimal getSessionid() {
        return this.sessionid;
    }
    
    public void setSessionid(BigDecimal sessionid) {
        this.sessionid = sessionid;
    }
    public Date getLstmoddttm() {
        return this.lstmoddttm;
    }
    
    public void setLstmoddttm(Date lstmoddttm) {
        this.lstmoddttm = lstmoddttm;
    }
    public Set getActivityDetails() {
        return this.activityDetails;
    }
    
    public void setActivityDetails(Set activityDetails) {
        this.activityDetails = activityDetails;
    }




}


