package com.mycompany.config.plan;
// Generated Feb 7, 2016 11:27:39 AM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * ActivityType generated by hbm2java
 */
@XmlType(name="ActivityType")
@XmlAccessorType(XmlAccessType.FIELD)
public class ActivityType  implements java.io.Serializable {

	 @XmlAttribute
     private String activitytypecode;
	 @XmlTransient
     private long version;
	 @XmlTransient
     private PermissionType permissionTypeByPermissionTypeCode;
	 @XmlTransient
     private PermissionType permissionTypeByRdnlyPermissionTypeCode;
	 @XmlAttribute
     private String displayname;
	 @XmlAttribute
     private String description;
	 @XmlTransient
     private String activityrenderer;
	 @XmlTransient
     private Boolean networked;
	 @XmlTransient
     private BigDecimal sessionid;
	 @XmlTransient
     private Date lstmoddttm;
	 @XmlTransient
     //@XmlElement(name="ActivityDefination")
     //@XmlElementWrapper
	 @JsonIgnore
     private Set<ActivityDefinition> activitydefinitions = new HashSet(0);
	 @XmlTransient
	 @JsonIgnore
     private Set activities = new HashSet(0);

    public ActivityType() {
    }

	
    public ActivityType(String activitytypecode, BigDecimal sessionid, Date lstmoddttm) {
        this.activitytypecode = activitytypecode;
        this.sessionid = sessionid;
        this.lstmoddttm = lstmoddttm;
    }
    public ActivityType(String activitytypecode, PermissionType permissionTypeByPermissionTypeCode, PermissionType permissionTypeByRdnlyPermissionTypeCode, String displayname, String description, String activityrenderer, Boolean networked, BigDecimal sessionid, Date lstmoddttm, Set activitydefinitions, Set activities) {
       this.activitytypecode = activitytypecode;
       this.permissionTypeByPermissionTypeCode = permissionTypeByPermissionTypeCode;
       this.permissionTypeByRdnlyPermissionTypeCode = permissionTypeByRdnlyPermissionTypeCode;
       this.displayname = displayname;
       this.description = description;
       this.activityrenderer = activityrenderer;
       this.networked = networked;
       this.sessionid = sessionid;
       this.lstmoddttm = lstmoddttm;
       this.activitydefinitions = activitydefinitions;
       this.activities = activities;
    }
   
    public String getActivitytypecode() {
        return this.activitytypecode;
    }
    
    public void setActivitytypecode(String activitytypecode) {
        this.activitytypecode = activitytypecode;
    }
    public long getVersion() {
        return this.version;
    }
    
    public void setVersion(long version) {
        this.version = version;
    }
    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
    public PermissionType getPermissionTypeByPermissionTypeCode() {
        return this.permissionTypeByPermissionTypeCode;
    }
    
    public void setPermissionTypeByPermissionTypeCode(PermissionType permissionTypeByPermissionTypeCode) {
        this.permissionTypeByPermissionTypeCode = permissionTypeByPermissionTypeCode;
    }
    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
    public PermissionType getPermissionTypeByRdnlyPermissionTypeCode() {
        return this.permissionTypeByRdnlyPermissionTypeCode;
    }
    
    public void setPermissionTypeByRdnlyPermissionTypeCode(PermissionType permissionTypeByRdnlyPermissionTypeCode) {
        this.permissionTypeByRdnlyPermissionTypeCode = permissionTypeByRdnlyPermissionTypeCode;
    }
    public String getDisplayname() {
        return this.displayname;
    }
    
    public void setDisplayname(String displayname) {
        this.displayname = displayname;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getActivityrenderer() {
        return this.activityrenderer;
    }
    
    public void setActivityrenderer(String activityrenderer) {
        this.activityrenderer = activityrenderer;
    }
    public Boolean getNetworked() {
        return this.networked;
    }
    
    public void setNetworked(Boolean networked) {
        this.networked = networked;
    }
    public BigDecimal getSessionid() {
        return this.sessionid;
    }
    
    public void setSessionid(BigDecimal sessionid) {
        this.sessionid = sessionid;
    }
    public Date getLstmoddttm() {
        return this.lstmoddttm;
    }
    
    public void setLstmoddttm(Date lstmoddttm) {
        this.lstmoddttm = lstmoddttm;
    }
    public Set<ActivityDefinition> getActivitydefinitions() {
        return this.activitydefinitions;
    }
    
    public void setActivitydefinitions(Set activitydefinitions) {
        this.activitydefinitions = activitydefinitions;
    }
    public Set getActivities() {
        return this.activities;
    }
    
    public void setActivities(Set activities) {
        this.activities = activities;
    }




}


