package com.mycompany.config.plan;
// Generated Feb 7, 2016 11:27:39 AM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * ActivityGroup generated by hbm2java
 */
@XmlType(name="ActivityGroup")
@XmlAccessorType(XmlAccessType.FIELD)
public class ActivityGroup  implements java.io.Serializable {

     @XmlTransient
     private BigDecimal activitygroupid;
     @XmlTransient
     private long version;
     @JsonIgnore
     @XmlTransient
     private Responsibility responsibility;
     @XmlElement(name = "display-name")
     private String title;
     @XmlTransient
     private String interface_;
     @XmlElement(name = "renderer")
     private String renderer;
     @XmlTransient
     private BigDecimal sessionid;
     @XmlTransient
     private Date lstmoddttm;
     @XmlTransient
     private Long position;
     @JsonIgnore
     @XmlElement(name="Activity")
     @XmlElementWrapper
     private Set<Activity> activities = new HashSet(0);

    public ActivityGroup() {
    }

	
    public ActivityGroup(BigDecimal activitygroupid, BigDecimal sessionid, Date lstmoddttm) {
        this.activitygroupid = activitygroupid;
        this.sessionid = sessionid;
        this.lstmoddttm = lstmoddttm;
    }
    public ActivityGroup(BigDecimal activitygroupid, Responsibility responsibility, String title, String interface_, String renderer, BigDecimal sessionid, Date lstmoddttm, Long position, Set activities) {
       this.activitygroupid = activitygroupid;
       this.responsibility = responsibility;
       this.title = title;
       this.interface_ = interface_;
       this.renderer = renderer;
       this.sessionid = sessionid;
       this.lstmoddttm = lstmoddttm;
       this.position = position;
       this.activities = activities;
    }
   
    public BigDecimal getActivitygroupid() {
        return this.activitygroupid;
    }
    
    public void setActivitygroupid(BigDecimal activitygroupid) {
        this.activitygroupid = activitygroupid;
    }
    public long getVersion() {
        return this.version;
    }
    
    public void setVersion(long version) {
        this.version = version;
    }
    public Responsibility getResponsibility() {
        return this.responsibility;
    }
    
    public void setResponsibility(Responsibility responsibility) {
        this.responsibility = responsibility;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getInterface_() {
        return this.interface_;
    }
    
    public void setInterface_(String interface_) {
        this.interface_ = interface_;
    }
    public String getRenderer() {
        return this.renderer;
    }
    
    public void setRenderer(String renderer) {
        this.renderer = renderer;
    }
    public BigDecimal getSessionid() {
        return this.sessionid;
    }
    
    public void setSessionid(BigDecimal sessionid) {
        this.sessionid = sessionid;
    }
    public Date getLstmoddttm() {
        return this.lstmoddttm;
    }
    
    public void setLstmoddttm(Date lstmoddttm) {
        this.lstmoddttm = lstmoddttm;
    }
    public Long getPosition() {
        return this.position;
    }
    
    public void setPosition(Long position) {
        this.position = position;
    }
    public Set<Activity> getActivities() {
        return this.activities;
    }
    
    public void setActivities(Set activities) {
        this.activities = activities;
    }




}


