package com.mycompany.config.plan;
// Generated Feb 7, 2016 11:27:39 AM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PermissionGroupType generated by hbm2java
 */
public class PermissionGroupType  implements java.io.Serializable {


     private String permissionGroupTypeCode;
     private long version;
     private Long displayorder;
     private String description;
     private BigDecimal sessionid;
     private Date lstmoddttm;
     private Set permissionTypes = new HashSet(0);

    public PermissionGroupType() {
    }

	
    public PermissionGroupType(String permissionGroupTypeCode, BigDecimal sessionid, Date lstmoddttm) {
        this.permissionGroupTypeCode = permissionGroupTypeCode;
        this.sessionid = sessionid;
        this.lstmoddttm = lstmoddttm;
    }
    public PermissionGroupType(String permissionGroupTypeCode, Long displayorder, String description, BigDecimal sessionid, Date lstmoddttm, Set permissionTypes) {
       this.permissionGroupTypeCode = permissionGroupTypeCode;
       this.displayorder = displayorder;
       this.description = description;
       this.sessionid = sessionid;
       this.lstmoddttm = lstmoddttm;
       this.permissionTypes = permissionTypes;
    }
   
    public String getPermissionGroupTypeCode() {
        return this.permissionGroupTypeCode;
    }
    
    public void setPermissionGroupTypeCode(String permissionGroupTypeCode) {
        this.permissionGroupTypeCode = permissionGroupTypeCode;
    }
    public long getVersion() {
        return this.version;
    }
    
    public void setVersion(long version) {
        this.version = version;
    }
    public Long getDisplayorder() {
        return this.displayorder;
    }
    
    public void setDisplayorder(Long displayorder) {
        this.displayorder = displayorder;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public BigDecimal getSessionid() {
        return this.sessionid;
    }
    
    public void setSessionid(BigDecimal sessionid) {
        this.sessionid = sessionid;
    }
    public Date getLstmoddttm() {
        return this.lstmoddttm;
    }
    
    public void setLstmoddttm(Date lstmoddttm) {
        this.lstmoddttm = lstmoddttm;
    }
    public Set getPermissionTypes() {
        return this.permissionTypes;
    }
    
    public void setPermissionTypes(Set permissionTypes) {
        this.permissionTypes = permissionTypes;
    }




}


