package com.mycompany.config.plan;
// Generated Feb 7, 2016 11:27:39 AM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PermissionCatType generated by hbm2java
 */
public class PermissionCatType  implements java.io.Serializable {


     private String permissioncattypecode;
     private long version;
     private String description;
     private BigDecimal sessionid;
     private Date lstmoddttm;
     private Set permissionTypes = new HashSet(0);

    public PermissionCatType() {
    }

	
    public PermissionCatType(String permissioncattypecode, BigDecimal sessionid, Date lstmoddttm) {
        this.permissioncattypecode = permissioncattypecode;
        this.sessionid = sessionid;
        this.lstmoddttm = lstmoddttm;
    }
    public PermissionCatType(String permissioncattypecode, String description, BigDecimal sessionid, Date lstmoddttm, Set permissionTypes) {
       this.permissioncattypecode = permissioncattypecode;
       this.description = description;
       this.sessionid = sessionid;
       this.lstmoddttm = lstmoddttm;
       this.permissionTypes = permissionTypes;
    }
   
    public String getPermissioncattypecode() {
        return this.permissioncattypecode;
    }
    
    public void setPermissioncattypecode(String permissioncattypecode) {
        this.permissioncattypecode = permissioncattypecode;
    }
    public long getVersion() {
        return this.version;
    }
    
    public void setVersion(long version) {
        this.version = version;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public BigDecimal getSessionid() {
        return this.sessionid;
    }
    
    public void setSessionid(BigDecimal sessionid) {
        this.sessionid = sessionid;
    }
    public Date getLstmoddttm() {
        return this.lstmoddttm;
    }
    
    public void setLstmoddttm(Date lstmoddttm) {
        this.lstmoddttm = lstmoddttm;
    }
    public Set getPermissionTypes() {
        return this.permissionTypes;
    }
    
    public void setPermissionTypes(Set permissionTypes) {
        this.permissionTypes = permissionTypes;
    }




}


