package com.mycompany.config.plan;
// Generated Feb 7, 2016 11:27:39 AM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;


/**
 * Plan generated by hbm2java
 */
@XmlRootElement(name="plan")
@XmlAccessorType(XmlAccessType.FIELD)
public class Plan  implements java.io.Serializable {

	 @XmlAttribute
     private BigDecimal planid;
	 @XmlTransient
     private long version;
     @XmlAttribute
     private String name;
     @XmlElement(name = "plan-type")
     private String planType;
     @XmlElement(name = "description")
     private String description;
     @XmlTransient
     private String conductorsp;
     @XmlElement(name="mod-version")
     private Long modversion;
     @XmlTransient
     private String categoryName;
     @XmlTransient
     private BigDecimal sessionid;
     @XmlElement(name="lstmoddttm")
     private Date lstmoddttm;
     @JsonIgnore
     //@XmlElement(name="Responsbility")
     //@XmlElementWrapper(name="responsbilities")
     @XmlTransient
     private Set<Responsibility> responsibilities = new HashSet(0);
     @JsonIgnore
     @XmlTransient
     private Set<PlanContext> planContexts = new HashSet(0);

    public Plan() {
    }

	
    public Plan(BigDecimal planid, BigDecimal sessionid, Date lstmoddttm) {
        this.planid = planid;
        this.sessionid = sessionid;
        this.lstmoddttm = lstmoddttm;
    }
    public Plan(BigDecimal planid, String name, String planType, String description, String conductorsp, Long modversion, String categoryName, BigDecimal sessionid, Date lstmoddttm, Set responsibilities, Set planContexts) {
       this.planid = planid;
       this.name = name;
       this.planType = planType;
       this.description = description;
       this.conductorsp = conductorsp;
       this.modversion = modversion;
       this.categoryName = categoryName;
       this.sessionid = sessionid;
       this.lstmoddttm = lstmoddttm;
       this.responsibilities = responsibilities;
       this.planContexts = planContexts;
    }
   
    public BigDecimal getPlanid() {
        return this.planid;
    }
    
    public void setPlanid(BigDecimal planid) {
        this.planid = planid;
    }
    public long getVersion() {
        return this.version;
    }
    
    public void setVersion(long version) {
        this.version = version;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPlanType() {
        return this.planType;
    }
    
    public void setPlanType(String planType) {
        this.planType = planType;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getConductorsp() {
        return this.conductorsp;
    }
    
    public void setConductorsp(String conductorsp) {
        this.conductorsp = conductorsp;
    }
    public Long getModversion() {
        return this.modversion;
    }
    
    public void setModversion(Long modversion) {
        this.modversion = modversion;
    }
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
    public BigDecimal getSessionid() {
        return this.sessionid;
    }
    
    public void setSessionid(BigDecimal sessionid) {
        this.sessionid = sessionid;
    }
    public Date getLstmoddttm() {
        return this.lstmoddttm;
    }
    
    public void setLstmoddttm(Date lstmoddttm) {
        this.lstmoddttm = lstmoddttm;
    }
    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
    public Set getResponsibilities() {
        return this.responsibilities;
    }
    
    public void setResponsibilities(Set responsibilities) {
        this.responsibilities = responsibilities;
    }
    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
    public Set getPlanContexts() {
        return this.planContexts;
    }
    
    public void setPlanContexts(Set planContexts) {
        this.planContexts = planContexts;
    }


	@Override
	public String toString() {
		return "Plan [planid=" + planid + ", name=" + name + "]";
	}




}


