package com.mycompany.config.plan;
// Generated Feb 7, 2016 11:27:39 AM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PlanContext generated by hbm2java
 */
public class PlanContext  implements java.io.Serializable {


     private BigDecimal planContextId;
     private long version;
     private Plan Plan;
     private String newstateconvopt;
     private boolean active;
     private String plantype;
     private BigDecimal serviceproviderid;
     private Long summaryscore1;
     private String summarystate1;
     private Long summaryscore2;
     private String summarystate2;
     private Long summaryscore3;
     private String summarystate3;
     private Long summaryscore4;
     private String summarystate4;
     private Long summaryscore5;
     private String summarystate5;
     private Long summaryscore6;
     private String summarystate6;
     private Long planmodversion;
     private BigDecimal regionidsys;
     private BigDecimal sessionid;
     private Date lstmoddttm;
     private BigDecimal loanapplicationid;
     private Set activityContexts = new HashSet(0);

    public PlanContext() {
    }

	
    public PlanContext(BigDecimal planContextId, Plan Plan, boolean active, String plantype, BigDecimal serviceproviderid, BigDecimal sessionid, Date lstmoddttm) {
        this.planContextId = planContextId;
        this.Plan = Plan;
        this.active = active;
        this.plantype = plantype;
        this.serviceproviderid = serviceproviderid;
        this.sessionid = sessionid;
        this.lstmoddttm = lstmoddttm;
    }
    public PlanContext(BigDecimal planContextId, Plan Plan, String newstateconvopt, boolean active, String plantype, BigDecimal serviceproviderid, Long summaryscore1, String summarystate1, Long summaryscore2, String summarystate2, Long summaryscore3, String summarystate3, Long summaryscore4, String summarystate4, Long summaryscore5, String summarystate5, Long summaryscore6, String summarystate6, Long planmodversion, BigDecimal regionidsys, BigDecimal sessionid, Date lstmoddttm, BigDecimal loanapplicationid, Set activityContexts) {
       this.planContextId = planContextId;
       this.Plan = Plan;
       this.newstateconvopt = newstateconvopt;
       this.active = active;
       this.plantype = plantype;
       this.serviceproviderid = serviceproviderid;
       this.summaryscore1 = summaryscore1;
       this.summarystate1 = summarystate1;
       this.summaryscore2 = summaryscore2;
       this.summarystate2 = summarystate2;
       this.summaryscore3 = summaryscore3;
       this.summarystate3 = summarystate3;
       this.summaryscore4 = summaryscore4;
       this.summarystate4 = summarystate4;
       this.summaryscore5 = summaryscore5;
       this.summarystate5 = summarystate5;
       this.summaryscore6 = summaryscore6;
       this.summarystate6 = summarystate6;
       this.planmodversion = planmodversion;
       this.regionidsys = regionidsys;
       this.sessionid = sessionid;
       this.lstmoddttm = lstmoddttm;
       this.loanapplicationid = loanapplicationid;
       this.activityContexts = activityContexts;
    }
   
    public BigDecimal getPlanContextId() {
        return this.planContextId;
    }
    
    public void setPlanContextId(BigDecimal planContextId) {
        this.planContextId = planContextId;
    }
    public long getVersion() {
        return this.version;
    }
    
    public void setVersion(long version) {
        this.version = version;
    }
    public Plan getPlan() {
        return this.Plan;
    }
    
    public void setPlan(Plan Plan) {
        this.Plan = Plan;
    }
    public String getNewstateconvopt() {
        return this.newstateconvopt;
    }
    
    public void setNewstateconvopt(String newstateconvopt) {
        this.newstateconvopt = newstateconvopt;
    }
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }
    public String getPlantype() {
        return this.plantype;
    }
    
    public void setPlantype(String plantype) {
        this.plantype = plantype;
    }
    public BigDecimal getServiceproviderid() {
        return this.serviceproviderid;
    }
    
    public void setServiceproviderid(BigDecimal serviceproviderid) {
        this.serviceproviderid = serviceproviderid;
    }
    public Long getSummaryscore1() {
        return this.summaryscore1;
    }
    
    public void setSummaryscore1(Long summaryscore1) {
        this.summaryscore1 = summaryscore1;
    }
    public String getSummarystate1() {
        return this.summarystate1;
    }
    
    public void setSummarystate1(String summarystate1) {
        this.summarystate1 = summarystate1;
    }
    public Long getSummaryscore2() {
        return this.summaryscore2;
    }
    
    public void setSummaryscore2(Long summaryscore2) {
        this.summaryscore2 = summaryscore2;
    }
    public String getSummarystate2() {
        return this.summarystate2;
    }
    
    public void setSummarystate2(String summarystate2) {
        this.summarystate2 = summarystate2;
    }
    public Long getSummaryscore3() {
        return this.summaryscore3;
    }
    
    public void setSummaryscore3(Long summaryscore3) {
        this.summaryscore3 = summaryscore3;
    }
    public String getSummarystate3() {
        return this.summarystate3;
    }
    
    public void setSummarystate3(String summarystate3) {
        this.summarystate3 = summarystate3;
    }
    public Long getSummaryscore4() {
        return this.summaryscore4;
    }
    
    public void setSummaryscore4(Long summaryscore4) {
        this.summaryscore4 = summaryscore4;
    }
    public String getSummarystate4() {
        return this.summarystate4;
    }
    
    public void setSummarystate4(String summarystate4) {
        this.summarystate4 = summarystate4;
    }
    public Long getSummaryscore5() {
        return this.summaryscore5;
    }
    
    public void setSummaryscore5(Long summaryscore5) {
        this.summaryscore5 = summaryscore5;
    }
    public String getSummarystate5() {
        return this.summarystate5;
    }
    
    public void setSummarystate5(String summarystate5) {
        this.summarystate5 = summarystate5;
    }
    public Long getSummaryscore6() {
        return this.summaryscore6;
    }
    
    public void setSummaryscore6(Long summaryscore6) {
        this.summaryscore6 = summaryscore6;
    }
    public String getSummarystate6() {
        return this.summarystate6;
    }
    
    public void setSummarystate6(String summarystate6) {
        this.summarystate6 = summarystate6;
    }
    public Long getPlanmodversion() {
        return this.planmodversion;
    }
    
    public void setPlanmodversion(Long planmodversion) {
        this.planmodversion = planmodversion;
    }
    public BigDecimal getRegionidsys() {
        return this.regionidsys;
    }
    
    public void setRegionidsys(BigDecimal regionidsys) {
        this.regionidsys = regionidsys;
    }
    public BigDecimal getSessionid() {
        return this.sessionid;
    }
    
    public void setSessionid(BigDecimal sessionid) {
        this.sessionid = sessionid;
    }
    public Date getLstmoddttm() {
        return this.lstmoddttm;
    }
    
    public void setLstmoddttm(Date lstmoddttm) {
        this.lstmoddttm = lstmoddttm;
    }
    public BigDecimal getLoanapplicationid() {
        return this.loanapplicationid;
    }
    
    public void setLoanapplicationid(BigDecimal loanapplicationid) {
        this.loanapplicationid = loanapplicationid;
    }
    public Set getActivityContexts() {
        return this.activityContexts;
    }
    
    public void setActivityContexts(Set activityContexts) {
        this.activityContexts = activityContexts;
    }




}


